### ISSUE TITLE
eregi() function was DEPRECATED

### ISSUE THREAD

**Issue by mohamedebrahim96** [gadgetguru/PHP-Streaming-Audio#7]
i have this error 
![rteterter](https://user-images.githubusercontent.com/16405013/34645811-c1079736-f35f-11e7-9c5e-507b4c5a441b.JPG)

**Comment by vkynchev** [comment]
Which version of pho are you using?

**Comment by mohamedebrahim96** [comment]
I'm using `PHP 7.1`
---------------------------------
eregi() function was DEPRECATED in PHP 5.3.0, and REMOVED in PHP 7.0.0. So  I must have to use [preg_match()](http://php.net/manual/en/function.preg-match.php)
 function instead of [eregi().](http://php.net/manual/en/function.eregi.php)
________________________
but when i fix it i found a lot of other errors and warnings

![ertertert](https://user-images.githubusercontent.com/16405013/34650902-325ce898-f3d1-11e7-9b95-05c733ed7082.JPG)

and the php code is 

![rwerwerewr](https://user-images.githubusercontent.com/16405013/34650922-ac09aa96-f3d1-11e7-9bbd-422d7231ccad.JPG)

**Comment by vkynchev** [comment]
Hmm...looks like these errors come from `$playfiles` not being initialized... If you are using my fork, you could try to fix this by deleting `temp.db` file in `music` directory.

**Comment by mohamedebrahim96** [comment]
thx a lot I'm now using your fork @vkynchev 
and it's work fine...
--------------------
 but I have little [lag/drop frames] on the sound

**Comment by vkynchev** [comment]
@mohamedebrahim96 try to set bitrate back to 96 from 160...

**Comment by mohamedebrahim96** [comment]
still, have little lag.
I wish I could make it stream like Spotify smoothly

**Comment by vkynchev** [comment]
@mohamedebrahim96 sounds like it's your internet connection... It streams fine on my local server, you could try adjusting PHP's memory limits.

**Comment by mohamedebrahim96** [comment]
Can I change music ....... he didn't identify different music other yours.
--
![image](https://user-images.githubusercontent.com/16405013/34652191-c118b78a-f3e3-11e7-8eb6-58f981ce1146.png)

**Comment by mohamedebrahim96** [comment]
I solve it by delete music.db
===============
