### ISSUE TITLE
Bad Documentation is a Killer

### ISSUE THREAD

**Issue by mohamedebrahim96** [gadgetguru/PHP-Streaming-Audio#8]
this documentation is too bad you don't clarify how to use files so i got a lot of errors

**Comment by vkynchev** [comment]
@mohamedebrahim96 Could you try my fork? I think that I fixed most errors and also created sub-folder scanning... However it was year ago, I can’t remember what exactly I’ve done...

**Comment by mohamedebrahim96** [comment]
WTF
--------------
your fork works like charm 

**thanks alot**
